print("Greetings!")
print("Greetings!")
print("Greetings!")
print("Greetings!")
print("Greetings!")
print("Greetings!")
print("Greetings!")

print("Parámetros")
args<-commandArgs(trailingOnly = TRUE)
print(args)
